### ISSUE TITLE
Upgraded spring boot version from 2.3.12.Release to 2.5.10, but API gateway is not able to register the service

### ISSUE THREAD

**Issue by saitejachintalapudi** [spring-cloud/spring-cloud-netflix#4073]
Getting Java.lang.NoSuchMethodError: 'com.google.common.base.Objects$ToStringHelper com.google.common.base.Objects.toStringHelper(Java.lang.Object)

Using below versions of dependencies in pom.xml
Spring boot version - 2.5.10
Spring cloud version - 20.0.5
Guava version - 30.0-jre
(For more info please find the below link: Getting same issue for me too: - https://stackoverflow.com/questions/68956756/springboot-upgrade)
When I keep guava version as 20.0, spring boot version is 2.3.12Release and spring cloud version is Hoxton.SR9 I can able to run the application. But now I can't able to run the application. Please help me to resolve the issue.

**Comment by OlgaMaciaszek** [comment]
Hello, @saitejachintalapudi - is the issue with Spring Cloud Netflix or Spring Cloud Gateway? In either case, we do not have Guava as a direct dependency, but it might be brought in as a transitive dependency from Netflix Eureka Client and GRPC.

**Comment by saitejachintalapudi** [comment]
Hello @OlgaMaciaszek, The issue is with Spring cloud Netflix. When I upgraded the spring boot version from 2.3.12.Release to 2.5.10, Application is not running, after finding Netflix - zuul is getting the issue. (https://stackoverflow.com/questions/68956756/springboot-upgrade) this link has more information about the issue what I'm facing.  If you got the issue please help me to resolve it.

**Comment by OlgaMaciaszek** [comment]
@saitejachintalapudi Spring Cloud Netflix Zuul is no longer supported. We recommend switching to [Spring Cloud Gateway](https://spring.io/projects/spring-cloud-gateway) instead.
