### ISSUE TITLE
spring-cloud-starter-eureka-server don't work with Gradle4

### ISSUE THREAD

**Issue by jguidoux** [spring-cloud/spring-cloud-netflix#2151]
Hello,

I try to use spring-cloud-starter-eureka-server with gradle.
To do that I just use http://start.spring.io/ to create an app with gradle, java8 and only eureka-server.

By default the the Gradle wrapper is set to version 3.5.1. And everything work with this version.
But, when I want to use Gradle 4.0.1, that don't work anymore, beaucse the embeded tomcat don't start.
```

java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
        at java.util.concurrent.FutureTask.report(FutureTask.java:122) [na:1.8.0_131]
        at java.util.concurrent.FutureTask.get(FutureTask.java:192) [na:1.8.0_131]
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:939) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:872) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.15.jar:8.5.15]
        ... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [Pipeline[StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[]]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5117) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.15.jar:8.5.15]
        ... 6 common frames omitted
Caused by: org.apache.catalina.LifecycleException: Failed to start component [org.apache.catalina.authenticator.NonLoginAuthenticator[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167) [tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.core.StandardPipeline.startInternal(StandardPipeline.java:182) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.15.jar:8.5.15]
        ... 8 common frames omitted
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;
        at org.apache.catalina.authenticator.AuthenticatorBase.startInternal(AuthenticatorBase.java:1141) ~[tomcat-embed-core-8.5.15.jar:8.5.15]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.15.jar:8.5.15]
        ... 10 common frames omitted

```
I look for this error, and I understood it is because spring-boot package the executive jar with servlet-api:2.5.

I can check it with the command : 

```
$ java -verbose:class -jar build/libs/eureka-server-0.0.1-SNAPSHOT.jar | grep javax.servlet.ServletContext 
[Loaded javax.servlet.ServletContext from jar:file:/home/jeremie/Téléchargements/eureka-server/build/libs/eureka-server-0.0.1-SNAPSHOT.jar!/BOOT-INF/lib/servlet-api-2.5.jar!/]
Caused by: java.lang.NoSuchMethodError: javax.servlet.ServletContext.getVirtualServerName()Ljava/lang/String;
```

If I build with gradle 3.5.1, servlet-api:2.5 is not use anymore.

I find a solution : 
```
  compile('org.springframework.cloud:spring-cloud-starter-eureka-server'){
		exclude module: 'servlet-api' //by artifact name
	}
```

But I thing it is not a good solution and that it is a bug.
I don't understand why suddenly a so old library is use. And why is is only the fact to choose the last version of Gradle which create this bug.

Thank you :)

**Comment by spencergibb** [comment]
Gradle 4 is not supported yet but is being worked on for spring boot 2

**Comment by jguidoux** [comment]
Thanks for your answer :)
