### ISSUE TITLE
Brixton.RC1 doesn't work with Spring Boot 1.3.0

### ISSUE THREAD

**Issue by OrangeDog** [spring-cloud/spring-cloud-netflix#943]
But does work with 1.3.2.
Currently the documentation says it works with 1.3.x, which is incorrect.

Exception that I get on application startup:
```
[ERROR] [main] 17:39:36.286 SpringApplication - Application startup failed
java.lang.NoSuchMethodError: org.springframework.util.ReflectionUtils.clearCache()V
	at org.springframework.context.support.AbstractApplicationContext.resetCommonCaches(AbstractApplicationContext.java:879) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:563) ~[spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:347) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.bootstrapServiceContext(BootstrapApplicationListener.java:140) [spring-cloud-context-1.1.0.RC2.jar:1.1.0.RC2]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:84) [spring-cloud-context-1.1.0.RC2.jar:1.1.0.RC2]
	at org.springframework.cloud.bootstrap.BootstrapApplicationListener.onApplicationEvent(BootstrapApplicationListener.java:1) [spring-cloud-context-1.1.0.RC2.jar:1.1.0.RC2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:163) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:136) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:119) [spring-context-4.2.5.RELEASE.jar:4.2.5.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.publishEvent(EventPublishingRunListener.java:111) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:65) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:54) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.doRun(SpringApplication.java:315) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:295) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:134) [spring-boot-1.3.0.RELEASE.jar:1.3.0.RELEASE]
	at myapp.Application.main(Application.java:27) [classes/:na]
```

My project has `spring-boot-starter-parent` as a parent, and imports `spring-cloud-dependencies`:

```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>1.3.0.RELEASE</version>
</parent>

<dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-dependencies</artifactId>
        <version>Brixton.RC1</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
</dependencyManagement>
```

**Comment by spencergibb** [comment]
What's happening is that you're getting mixed versions of spring
```
[INFO] |  +- org.springframework:spring-web:jar:4.2.5.RELEASE:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:4.2.5.RELEASE:compile
[INFO] |  |  |  \- aopalliance:aopalliance:jar:1.0:compile
[INFO] |  |  +- org.springframework:spring-beans:jar:4.2.5.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-context:jar:4.2.5.RELEASE:compile
[INFO] |  \- org.springframework:spring-webmvc:jar:4.2.5.RELEASE:compile
[INFO] |     \- org.springframework:spring-expression:jar:4.2.5.RELEASE:compile
[INFO] \- org.springframework.boot:spring-boot-starter-test:jar:1.3.0.RELEASE:test
[INFO]    +- junit:junit:jar:4.12:test
[INFO]    +- org.mockito:mockito-core:jar:1.10.19:test
[INFO]    |  \- org.objenesis:objenesis:jar:2.1:test
[INFO]    +- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO]    +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO]    +- org.springframework:spring-core:jar:4.2.3.RELEASE:compile
[INFO]    \- org.springframework:spring-test:jar:4.2.5.RELEASE:test
```
You can see 4.2.3 and 4.2.5 which will cause problems. Pinning to one version or another is your workaround.

**Comment by OrangeDog** [comment]
Indeed, but shouldn't your (i.e. spring's) dependency management be dealing with that?

**Comment by spencergibb** [comment]
It usually does. Sitting next to @philwebb of spring-boot and it's weirding us out.

**Comment by spencergibb** [comment]
Adding this above the spring cloud BOM fixes it.

			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-dependencies</artifactId>
				<version>1.3.0.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

@smaldini @dsyer is that what start.spring.io should be doing?

**Comment by spencergibb** [comment]
@snicoll trying to ping the right Stéphane ;-)

**Comment by snicoll** [comment]
I thought that issue was fixed. I guess we need to look into it again. Is there a sample project available?

**Comment by spencergibb** [comment]
@snicoll I just used http://start.spring.io selected Web and Config Client, then changed the boot version to 1.3.0 and ran, you'll see the error.

**Comment by dsyer** [comment]
Whatever the ins and outs of this particular build, it doesn't make any sense to use 1.3.0 with Brixton when 1.3.3 is already released. Just upgrade, already.

**Comment by snicoll** [comment]
I've tested with Maven `3.4.0.BUILD-SNAPSHOT` that fixes bom imports and the project uses Spring Framework 4.2.5 and Spring Boot 1.3.3. Which means that the `spring-cloud-dependencies` bom brings dependnecy management for Spring Boot again. It shouldn't.

**Comment by snicoll** [comment]
Scratch that, I got confused again. This is the `spring-core` glitch we never managed to fix (but it's fixed in Maven `3.4` snapshots. The BOM workaround is the only known option that works. Maybe we should document that in bold red somewhere?

**Comment by dsyer** [comment]
I think there's another option which is to change the parent pom, but that gets really fiddly if you want Spring Boot 1.3.0 and Brixton.RC1 (there's no parent that we publish out of the box with that combination).
